name: Labeling new issue
on:
  issues:
    types: ["opened"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2.1.3
        with:
          repo-token: ${{ secrets.USER_TOKEN }}
          labels-not-allowed: '["Stale","Pendente de informações","Falta de informações"]'
